name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name : Clean
        run: git clean -xdf
      - name: Build DotNET35
        run: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
            .\MSBuild.exe $Env:GITHUB_WORKSPACE\KingOfTokyo\KingOfTokyo.sln
      - name: Upload Serveur
        uses: actions/upload-artifact@v1
        with:
          name: ServeurKoT
          path: $Env:GITHUB_WORKSPACE\KingOfTokyo\ServeurKoT\bin
      - name: Upload Client
        uses: actions/upload-artifact@v1
        with:
          name: ClientKoT
          path: $Env:GITHUB_WORKSPACE\KingOfTokyo\ClientKoT\bin

